version: '3.8'

services:
  postgres:
    container_name: "minqyy-postgres"
    image: "postgres:latest"
    restart: unless-stopped
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  redis:
    container_name: "minqyy-redis"
    image: "redis/redis-stack-server:latest"
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS

  minqyy-api:
    container_name: "minqyy-api"
    image: "minqyy-api:latest"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      - CONFIG_PATH=./config/dev.yaml