env: "dev" # local | dev | prod

server:
  address: "0.0.0.0:6969"
  timeout: 4s
  idle_timeout: 60s

token:
  access:
    secret: "some-secret-key"
    ttl: 15m
  refresh:
    ttl: 720h

hasher:
  salt: "salt-for-password-hash"

postgres:
  host: ""
  port: ""
  user: ""
  name: ""
  password: ""
  sslmode: ""

redis:
  host: ""
  username: ""
  password: ""